spring:
  application:
    name: fun-config-server
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username: xuanag
          password: 123


logging:
  path: E:/log