spring:
  application:
    name: fun-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloudgc/cloud
          search-paths: learn/config
          username: xuanag
          password: 123



logging:
  path: E:/log